### ISSUE TITLE
EIP-155: design problem in unique chain IDs

### ISSUE THREAD

**Issue by lukaszmatczak** [ethereum/EIPs#1747] opened 2019-02-11 09:19 UTC
EIP-155 requires that different chains must have unique chain ID. Specification contains list of chains with their IDs, but it turns out that this list is incomplete and contains only biggest chains. There's no official full list (I think we can't assume that https://github.com/ethereum-lists/chains is official list because it's not mentioned in EIP-155).

Requiring unique ID without providing list of used IDs looks like serious design problem in EIP-155. There's no way to check if given chain ID is free. As a result, there may appear conflicts like https://github.com/ethereum-lists/chains/issues/25

To resolve this issue I propose to include full list in EIP-155 or create an official list somewhere and insert link to it in specification.

**Comment by ligi** [comment] 2019-02-11 10:05
> I think we can't assume that https://github.com/ethereum-lists/chains is official list because it's not mentioned in EIP-155)

I opened a PR about a month ago to add it: https://github.com/ethereum/EIPs/pull/1703

Not to make it official (I think in a decentralized word this word is very problematic) - but to avoid collisions by making people aware of other chain ids.

There was no signal yet against it - but it did not get merged yet. The problem is EIP155 is done by @vbuterin - so he need to approve to merge - but I think he has more important things to do.

Adding all chains via PRs to ethereum/EIPs sounds like a big overhead and will make EIP numbers even larger. Especially with so many chains popping up over time.

**Comment by nicksavers** [comment] 2019-03-08 11:22
Hopefully resolved through #1703

**Closed by nicksavers** 2019-03-08 11:22 UTC
