### ISSUE TITLE
@eth-bot gives EIP file name error problem for new submission

### ISSUE THREAD

**Issue by julesl23** [ethereum/EIPs#4398] opened 2021-10-29 20:17 UTC
@poojaranjan this is intended behavior when a file is not named correctly. What behavior would you prefer? Also please open a issue in eth-bot 😊

_Originally posted by @alita-moore in https://github.com/ethereum/EIPs/issues/4393#issuecomment-955003257_

The pull request link https://github.com/ethereum/EIPs/pull/4393 with the problem

@eth-bot

The documentation from https://github.com/ethereum/EIPs/blob/master/eip-template.md
specifies "When opening a pull request to submit your EIP, please use an abbreviated title in the filename, eip-draft_title_abbrev.md."

When I do that, eth-bot returns with error "Error: EIP file name must be eip-###.md"

I don't know which is correct. But neither didn't seem to work with me and gives  

Auto-Merge Bot / EIP Auto-Merge Bot (pull_request_target) Failing after 27s — EIP Auto-Merge Details

Clicking details highlights the line
Error: EIP file name must be eip-###.md

**Comment by alita-moore** [comment] 2021-10-29 20:18
Very descriptive. Thank you!

**Comment by alita-moore** [comment] 2021-11-27 02:15
@poojaranjan @julesl23 this is intended behavior. all eip's should be assigned eip numbers before they are merged initially. Can I close this?

**Comment by MicahZoltu** [comment] 2021-11-27 05:51
When the PR is originally opened it will *not* have an EIP number.  An editor will assign an EIP number after the PR is created.  The current behavior results in an error for every correctly constructed new EIP, which is mildly annoying.  Can we look for the recommended filename of `eip-draft_title_abbrev.md` and special case that to give a more clear message like this?
> @editor1 @editor2 please assign this EIP a number so the author can update this PR with it.

**Comment by alita-moore** [comment] 2021-11-27 18:43
Sure @MicahZoltu I'll add this feature

**Comment by alita-moore** [comment] 2021-11-28 22:53
okay so as an update [this](https://github.com/ethereum/EIP-Bot/compare/9b68698077d01a4b434249818b663b90eb68983c...bc4ee87a1e3a92bf92beb210c64381b34cf16df4) implements the requested feature. In particular it checks that

1. the file is new
2. there is no eip number already associated with the file
3. that the file is in eip-.*_*.md format
4. if above are met it will mention all editors and offer an explanation to the submitter
5. I added a clarification in the file formatting issue where it informs users about this feature as well

**Comment by alita-moore** [comment] 2021-11-28 22:55
because I believe this meets all requirements I wlll close this issue. I will follow up on this if more problems arise.

**Closed by alita-moore** 2021-11-28 22:55 UTC
