### ISSUE TITLE
Website: show permalink on mouseover

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1314] opened 2018-08-12 02:52 UTC
On GitHub, if you mouseover a H1 or H2... heading then you will see a permalink on the left which links directly to that anchor. This is helpful referencing documentation in EIPs because yon can link to the specific text that is relevant.

Now that we have switched from GitHub code repository to the EIP website as being the canonical place to cite EIPS, I would like to request the same feature there.

Additionally, I would like to ask for paragraph-specific selectors if possible. The text of web pages on EIPS.ethereum.org are likely to stay unchanged for a long time. So it will be helpful to link to specific paragraphs if we can.

I'm doing smart contract audits now, it is great to link to the specific thing that illustrates problems in my findings.

**Comment by axic** [comment] 2020-08-28 19:21
I think this issue is a duplicate of #1106. #2581 addresses this problem.

Since it is a duplicate I'm closing this issue now, but feel free to reopen if I misjudged it.

**Closed by axic** 2020-08-28 19:21 UTC
Labels: type: Meta
