### ISSUE TITLE
Update mobile layout to wrap vs. overflow

### ISSUE THREAD

**Issue by samajammin** [ethereum/EIPs#3604] opened 2021-06-07 19:44 UTC
This issue is specific to the web application eips.ethereum.org.

Some pages (e.g. https://eips.ethereum.org/EIPS/eip-721) display poorly on mobile. See:
https://twitter.com/yugacohler/status/1393606548337958918

This appears to be caused the the table of metadata at the top of pages. I bet this could be fixed with a relatively simple CSS update to force the table to wrap vs. overflow. The goal should be to constrain all mobile content to 100% page width in order to avoid any content overflow.

**Comment by MicahZoltu** [comment] 2021-06-08 00:58
I am unable to reproduce that behavior in Firefox desktop's mobile simulator.  My best guess is that this problem is caused by Safari once again making the internet a worse place by not following standards (I have a seething hatred for Safari, much akin to Internet Explorer 6).

**Comment by timbeiko** [comment] 2021-08-25 15:32
It looks good for me using Safari on iPhone, see a few screenshots. I'll ping Yuga to see what he was using. 
![IMG_0466](https://user-images.githubusercontent.com/9390255/130820222-1d8283bf-7a4f-438e-8797-8a5928f7b71f.PNG)
![IMG_0467](https://user-images.githubusercontent.com/9390255/130820229-87c01c49-0d2c-4ecd-91bd-1d5c7f65a878.PNG)
![IMG_0468](https://user-images.githubusercontent.com/9390255/130820235-384293ef-0ae8-422b-b8bd-15fea8b0c3d3.PNG)
![IMG_0469](https://user-images.githubusercontent.com/9390255/130820244-1de90c03-3d28-4122-9fc1-5db9e22c1d2b.PNG)

**Comment by MicahZoltu** [comment] 2021-08-28 07:33
I'm going to close this for now, feel free to reopen if you are still experiencing the issue and can help provide some additional troubleshooting information.

**Closed by MicahZoltu** 2021-08-28 07:33 UTC
