### ISSUE TITLE
Add a CLA

### ISSUE THREAD

**Issue by Limpisey77922321** [ethereum/EIPs#7510] opened 2023-08-21 18:34 UTC
### Suggestion

The inclusion of a Larger Works concept facilitates use of a contributor license agreement (CLA), with contributors granting a patent license to the works to which they're contributing, and therefore creating a common & safe platform for collaboration where no one is going to assert infringement by the same project in which they're an active participant.

**Comment by Ramezaan7** [comment] 2023-08-27 15:36
EIPS/eip-20.md

**Comment by SamWilsn** [comment] 2023-08-30 15:49
This is a duplicate of https://github.com/ethereum/EIPs/issues/5662

**Closed by SamWilsn** 2023-08-30 15:49 UTC
Labels: enhancement
